export const clerkAppearance = {
  variables: {
    colorPrimary: "#6366f1",
    colorBackground: "transparent",
    colorText: "#e6edf3",
    colorTextSecondary: "#8b949e",
    colorInputBackground: "rgba(10, 14, 22, 0.6)",
    colorInputText: "#e6edf3",
    colorDanger: "#ff7b72",
    colorSuccess: "#3fb950",
    borderRadius: "10px",
    fontSize: "14px",
  },
  elements: {
    rootBox: "auth-clerk-root",
    card: "auth-clerk-card",
    headerTitle: "auth-clerk-hidden",
    headerSubtitle: "auth-clerk-hidden",
    logoBox: "auth-clerk-hidden",
    main: "auth-clerk-main",
    socialButtonsBlockButton: "auth-clerk-social-btn",
    socialButtonsBlockButtonText: "auth-clerk-social-btn-text",
    socialButtonsProviderIcon: "auth-clerk-social-icon",
    dividerLine: "auth-clerk-divider-line",
    dividerText: "auth-clerk-divider-text",
    formFieldLabel: "auth-clerk-label",
    formFieldInput: "auth-clerk-input",
    formFieldInputShowPasswordButton: "auth-clerk-show-pwd",
    formButtonPrimary: "auth-clerk-primary-btn",
    formResendCodeLink: "auth-clerk-link",
    footer: "auth-clerk-hidden",
    footerAction: "auth-clerk-hidden",
    footerActionLink: "auth-clerk-link",
    identityPreviewEditButton: "auth-clerk-link",
    formFieldAction: "auth-clerk-link",
    otpCodeFieldInput: "auth-clerk-otp",
    alert: "auth-clerk-alert",
    alertText: "auth-clerk-alert-text",
    formFieldErrorText: "auth-clerk-error",
    formFieldSuccessText: "auth-clerk-success",
    formFieldWarningText: "auth-clerk-warning",
    spinner: "auth-clerk-spinner",
  },
  layout: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    showOptionalFields: false,
  },
};
